version: "3.8"

services:
  chatbot-cli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-cli
    env_file: .env
    command: python main.py
    stdin_open: true
    tty: true

  chatbot-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-ui
    env_file: .env
    command: streamlit run app.py --server.port=8501 --server.enableCORS=false
    ports:
      - "8501:8501"
